import XCTest
@testable import VanguardApple

/// Swift's real output must pass the hub's real validator (`hub/native-contract.test.js` checks the same file).
/// A stubbed hub cannot catch encoding mismatches, such as a finding that omits `"value": null`.
final class HubContractTests: XCTestCase {
    private var fixture: URL { URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("../../../../docs/fixtures/native-processing-v1.json") }

    private func envelope() throws -> [String: Any] {
        let transcript = "May lalaki po dito, around 60 years old. Nahihirapan siyang huminga at masakit yung dibdib niya. Mga 30 minutes na. Sa Barangay Uno, sampung minuto papunta sa ospital."
        var processing = try NativeProcessing.validated(generated: "{\"consciousness\":\"alert\",\"breathing\":\"abnormal\",\"evidence\":{}}", transcript: transcript,
                                                        device: .appleWatch, sttEngine: "SFSpeechRecognizer/on-device", artifact: VoiceStoreTests.artifact)
        let extracted = ReportExtraction.extract(transcript: transcript, pack: try TermPack.bundled())
        processing.findings = extracted.findings
        var object = try JSONSerialization.jsonObject(with: JSONEncoder().encode(processing)) as! [String: Any]
        var provenance = object["provenance"] as! [String: Any]
        provenance["sttRuntime"] = "fixture-os"            // the real value is the host OS version string
        object["provenance"] = provenance
        return ["_note": "Generated by HubContractTests (VANGUARD_WRITE_FIXTURE=1). hub/native-contract.test.js validates it with the hub's real validator.",
                "extraction": ["details": try JSONSerialization.jsonObject(with: JSONEncoder().encode(extracted.details))], "processing": object]
    }

    func testSwiftProcessingEnvelopeMatchesTheHubContractFixture() throws {
        let produced = try envelope()
        if ProcessInfo.processInfo.environment["VANGUARD_WRITE_FIXTURE"] == "1" {
            try JSONSerialization.data(withJSONObject: produced, options: [.prettyPrinted, .sortedKeys]).write(to: fixture)
        }
        let stored = try JSONSerialization.jsonObject(with: Data(contentsOf: fixture)) as! [String: Any]
        XCTAssertEqual(NSDictionary(dictionary: stored), NSDictionary(dictionary: produced),
                       "Swift's processing encoding changed: regenerate with VANGUARD_WRITE_FIXTURE=1 and let the hub test validate it")
        let processing = try XCTUnwrap(stored["processing"] as? [String: Any])
        let findings = try XCTUnwrap(processing["findings"] as? [[String: Any]])
        XCTAssertFalse(findings.isEmpty)
        for finding in findings { XCTAssertNotNil(finding["value"], "every finding carries an explicit value or null") }
    }
}
